### ISSUE TITLE
外贸盒子T95max选择哪个版本呢？

### ISSUE THREAD

**Issue by Payniu** [ophub/amlogic-s9xxx-armbian#1383] opened 2023-05-08 15:04 UTC
请教一下，T95max allwinner h6芯片，下载[Armbian_23.05.0_allwinner_tanix-tx6_jammy_6.1.27_server_2023.05.07.img.gz]这个安装后网卡无法获取到IP，请问还有哪个固件可以适配这个机顶盒？谢谢

**Comment by piotr-zemla** [comment] 2023-05-08 19:00
Possible duplicate of [this](https://github.com/ophub/amlogic-s9xxx-armbian/issues/1331) issue.

100 MBit ethernet chips (EMAC) for H6 are currently broken with kernels supplied by ophub. (They may also be broken in mainline; I'll check, if I ever get to compile one)

T95Max seems to be very similiar to Tanix TX6 TV boxes, [Inovato's](https://www.inovato.net/Armbian/) images seem to have the best kernel for this type of a TV Box.

I can also recommend buying a Ethernet dongle to USB. You can at least keep using an updated kernel.

**Comment by ophub** [comment] 2023-05-09 00:33
@piotr-zemla 

The kernel source code I'm using is located at: https://github.com/unifreq/linux-6.1.y
Could you please take a look and help me debug and fix the issue?

**Comment by piotr-zemla** [comment] 2023-05-09 07:50
> @piotr-zemla
> 
> The kernel source code I'm using is located at: https://github.com/unifreq/linux-6.1.y Could you please take a look and help me debug and fix the issue?

I'm working on it.

**Comment by piotr-zemla** [comment] 2023-05-12 16:27
@ophub @Payniu

Compiled a couple versions of the mainline kernel, only older versions would give any HDMI output. Everything Linux 6.1+ should be considered completely broken.
I'm going to try to gather some more debug information, and write up an issue concerning support of this device in mainline kernel. Hopefully someone there will find time to fix it.

I won't fix it myself, that's for sure; I have absolutely no experience in this matter.  My Linux skills don't extend further than compiling and installing parts of the system.

**Comment by ophub** [comment] 2023-05-12 23:07
You can test whether the 5.15.y kernel can be used normally. Test wired network card and hdmi

**Closed** 2023-05-18 00:51 UTC

**Comment by Payniu** [comment] 2023-05-23 08:12
> You can test whether the 5.15.y kernel can be used normally. Test wired network card and hdmi

能否提供Armbian_23.05.0_allwinner_tanix-tx6_bullseye_5.15.108_server_2023.04.25.img.gz这个版本我重新下载测试一下呢

**Comment by ophub** [comment] 2023-05-23 08:40
删了

**Comment by Payniu** [comment] 2023-05-23 09:54
> 删了，没了。

5.15.x其他版本有吗？
